import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import Header from "../components/Layout";
import Section2 from "../components/Section2";
import Section3 from "../components/Section3";
import Section4 from "../components/Section4";
import Section5 from "../components/Section5";
import Section6 from "../components/Section6";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className=" max-w-[80%] mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-20 mx-auto">
        <div>
          <div className="md:flex justify-between mt-12 ">
            <div className="flex justify-center md:justify-start">
              <div className="h-80% w-[60%] md:w-auto  items-end">
                <Image
                  alt="crown"
                  src={"image 4.svg"}
                  width="500"
                  height="500"
                ></Image>
              </div>
            </div>

            <div className="absolute left-0 top-10 md:top-52 md:left-0 md:hidden">
              <Image
                alt="centerImg"
                src="/crown.svg"
                width={100}
                height="100"
                className="md:w-[200px]"
              ></Image>
            </div>
            <div>
              <div className="md:w-[80%] w-full mx-auto h-full">
                <h1 className="text-3xl lg:text-5xl xl:text-6xl  text-[#010721]  font font-josefin_bold text-center md:text-left leading-10">
                  Ýatdan çykmajak pursatlar plansyz bolmaýar.
                </h1>
                <div className="my-4">
                  <p className="text-center md:text-left leading-7 font-helvetica font-[400] md:w-[70%] w-full text-xl">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
                    venenatis tempor vitae morbi tempus. Nisl imperdiet et ac
                    enim. Cras sed commodo vulputate curabitur
                  </p>
                </div>
                <div className="flex justify-between md:justify-start items-end h-[28%] ">
                  <Button
                    text={"Biz bilen habarlas"}
                    buttonStyle={"w-full md:w-[60%]"}
                  />
                </div>
              </div>
            </div>
          </div>
          <div className="absolute right-0 top-10 md:top-52 md:right-0 ">
            <Image
              alt="imgLeft"
              src="/righHeroImg.svg"
              width={200}
              height="200"
            ></Image>
          </div>
        </div>
      </main>

      <section className="">
        <Section2 />
      </section>

      <section className="">
        <Section3 />
      </section>
      <section className="">
        <Section4 />
      </section>

      <section className="">
        <Section5 />
      </section>
      <section className="">
        <Section6 />
      </section>
    </div>
  );
}
